/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Quantitative Trading Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface MarketPrice {
  symbol: string;
  price: number;
  change24h: number;
  changePercent24h: number;
  volume24h: number;
  high24h: number;
  low24h: number;
  timestamp: string;
}

export interface Candle {
  timestamp: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

export interface CandleData {
  symbol: string;
  candles: Candle[];
}

export interface ForecastOutput {
  symbol: string;
  /** Probability of upward price movement (0-1) */
  directionProbability: number;
  /** Expected price range in USD */
  expectedRange: number;
  /** Distance to next predicted high in USD */
  nextHighDistance: number;
  /** Distance to next predicted low in USD */
  nextLowDistance: number;
  /** Model confidence score (0-1) */
  modelConfidence: number;
  /** Forecast time horizon (e.g., 4h, 1d) */
  horizon: string;
  timestamp: string;
}

export type AgentDecisionOutputConsensusIntent =
  (typeof AgentDecisionOutputConsensusIntent)[keyof typeof AgentDecisionOutputConsensusIntent];

export const AgentDecisionOutputConsensusIntent = {
  BUY: "BUY",
  SELL: "SELL",
  HOLD: "HOLD",
} as const;

export type SingleAgentDecisionTradeIntent =
  (typeof SingleAgentDecisionTradeIntent)[keyof typeof SingleAgentDecisionTradeIntent];

export const SingleAgentDecisionTradeIntent = {
  BUY: "BUY",
  SELL: "SELL",
  HOLD: "HOLD",
} as const;

export interface SingleAgentDecision {
  agentId: string;
  tradeIntent: SingleAgentDecisionTradeIntent;
  /** Directional bias from -1 (strong sell) to 1 (strong buy) */
  directionBias: number;
  /** Risk score from 0 (low risk) to 1 (high risk) */
  riskScore: number;
  /** Exit urgency score from 0 to 1 */
  exitBias: number;
  /** NEAT fitness score */
  fitness: number;
}

export interface AgentDecisionOutput {
  symbol: string;
  agents: SingleAgentDecision[];
  consensusIntent: AgentDecisionOutputConsensusIntent;
  consensusScore: number;
  timestamp: string;
}

export type AggregationOutputRegime =
  (typeof AggregationOutputRegime)[keyof typeof AggregationOutputRegime];

export const AggregationOutputRegime = {
  TRENDING: "TRENDING",
  RANGING: "RANGING",
  VOLATILE: "VOLATILE",
  BREAKOUT: "BREAKOUT",
} as const;

export type AggregationOutputSignalLabel =
  (typeof AggregationOutputSignalLabel)[keyof typeof AggregationOutputSignalLabel];

export const AggregationOutputSignalLabel = {
  STRONG_BUY: "STRONG_BUY",
  BUY: "BUY",
  NEUTRAL: "NEUTRAL",
  SELL: "SELL",
  STRONG_SELL: "STRONG_SELL",
} as const;

export interface AgentWeights {
  lstmWeight: number;
  neatWeight: number;
  momentumWeight: number;
  meanReversionWeight: number;
}

export interface AggregationOutput {
  symbol: string;
  regime: AggregationOutputRegime;
  weights: AgentWeights;
  /** Aggregated signal from -1 to 1 */
  aggregatedSignal: number;
  signalLabel: AggregationOutputSignalLabel;
  regimeConfidence: number;
  timestamp: string;
}

export interface ReasoningOutput {
  symbol: string;
  /** Market context classification label */
  contextLabel: string;
  /** Overall reasoning confidence (0-1) */
  confidenceScore: number;
  /** Whether reasoning layer vetoes the current signal */
  vetoSignal: boolean;
  vetoReason?: string | null;
  /** Structured reasoning narrative */
  reasoningSummary: string;
  keyFactors: string[];
  riskWarnings: string[];
  timestamp: string;
}

export type FinalDecisionOutputAction =
  (typeof FinalDecisionOutputAction)[keyof typeof FinalDecisionOutputAction];

export const FinalDecisionOutputAction = {
  BUY: "BUY",
  SELL: "SELL",
  HOLD: "HOLD",
  VETO: "VETO",
} as const;

export type LayerVotesLstmVote =
  (typeof LayerVotesLstmVote)[keyof typeof LayerVotesLstmVote];

export const LayerVotesLstmVote = {
  BUY: "BUY",
  SELL: "SELL",
  HOLD: "HOLD",
} as const;

export type LayerVotesAgentVote =
  (typeof LayerVotesAgentVote)[keyof typeof LayerVotesAgentVote];

export const LayerVotesAgentVote = {
  BUY: "BUY",
  SELL: "SELL",
  HOLD: "HOLD",
} as const;

export type LayerVotesAggregationVote =
  (typeof LayerVotesAggregationVote)[keyof typeof LayerVotesAggregationVote];

export const LayerVotesAggregationVote = {
  BUY: "BUY",
  SELL: "SELL",
  HOLD: "HOLD",
} as const;

export type LayerVotesReasoningVote =
  (typeof LayerVotesReasoningVote)[keyof typeof LayerVotesReasoningVote];

export const LayerVotesReasoningVote = {
  BUY: "BUY",
  SELL: "SELL",
  HOLD: "HOLD",
  VETO: "VETO",
} as const;

export interface LayerVotes {
  lstmVote: LayerVotesLstmVote;
  agentVote: LayerVotesAgentVote;
  aggregationVote: LayerVotesAggregationVote;
  reasoningVote: LayerVotesReasoningVote;
}

export interface FinalDecisionOutput {
  symbol: string;
  action: FinalDecisionOutputAction;
  /** Final decision confidence (0-1) */
  confidence: number;
  /** Recommended position size as fraction of portfolio (0-1) */
  positionSize: number;
  /** Suggested stop-loss price */
  stopLoss: number;
  /** Suggested take-profit price */
  takeProfit: number;
  riskRewardRatio: number;
  layerVotes: LayerVotes;
  executionRecommendation: string;
  timestamp: string;
}

export type GetMarketPriceParams = {
  symbol?: string;
};

export type GetMarketCandlesParams = {
  symbol?: string;
  limit?: number;
};

export type GetForecastParams = {
  symbol?: string;
};

export type GetAgentDecisionParams = {
  symbol?: string;
};

export type GetAggregationParams = {
  symbol?: string;
};

export type GetReasoningParams = {
  symbol?: string;
};

export type GetFinalDecisionParams = {
  symbol?: string;
};
