/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Quantitative Trading Intelligence Platform API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AgentDecisionOutput,
  AggregationOutput,
  CandleData,
  FinalDecisionOutput,
  ForecastOutput,
  GetAgentDecisionParams,
  GetAggregationParams,
  GetFinalDecisionParams,
  GetForecastParams,
  GetMarketCandlesParams,
  GetMarketPriceParams,
  GetReasoningParams,
  HealthStatus,
  MarketPrice,
  ReasoningOutput,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns current price, OHLCV, and symbol info
 * @summary Get current market price data
 */
export const getGetMarketPriceUrl = (params?: GetMarketPriceParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/market/price?${stringifiedParams}`
    : `/api/market/price`;
};

export const getMarketPrice = async (
  params?: GetMarketPriceParams,
  options?: RequestInit,
): Promise<MarketPrice> => {
  return customFetch<MarketPrice>(getGetMarketPriceUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetMarketPriceQueryKey = (params?: GetMarketPriceParams) => {
  return [`/api/market/price`, ...(params ? [params] : [])] as const;
};

export const getGetMarketPriceQueryOptions = <
  TData = Awaited<ReturnType<typeof getMarketPrice>>,
  TError = ErrorType<unknown>,
>(
  params?: GetMarketPriceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMarketPrice>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMarketPriceQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMarketPrice>>> = ({
    signal,
  }) => getMarketPrice(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMarketPrice>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMarketPriceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMarketPrice>>
>;
export type GetMarketPriceQueryError = ErrorType<unknown>;

/**
 * @summary Get current market price data
 */

export function useGetMarketPrice<
  TData = Awaited<ReturnType<typeof getMarketPrice>>,
  TError = ErrorType<unknown>,
>(
  params?: GetMarketPriceParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMarketPrice>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMarketPriceQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns historical OHLCV candles for charting
 * @summary Get OHLCV candle data
 */
export const getGetMarketCandlesUrl = (params?: GetMarketCandlesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/market/candles?${stringifiedParams}`
    : `/api/market/candles`;
};

export const getMarketCandles = async (
  params?: GetMarketCandlesParams,
  options?: RequestInit,
): Promise<CandleData> => {
  return customFetch<CandleData>(getGetMarketCandlesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetMarketCandlesQueryKey = (
  params?: GetMarketCandlesParams,
) => {
  return [`/api/market/candles`, ...(params ? [params] : [])] as const;
};

export const getGetMarketCandlesQueryOptions = <
  TData = Awaited<ReturnType<typeof getMarketCandles>>,
  TError = ErrorType<unknown>,
>(
  params?: GetMarketCandlesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMarketCandles>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMarketCandlesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMarketCandles>>
  > = ({ signal }) => getMarketCandles(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMarketCandles>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMarketCandlesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMarketCandles>>
>;
export type GetMarketCandlesQueryError = ErrorType<unknown>;

/**
 * @summary Get OHLCV candle data
 */

export function useGetMarketCandles<
  TData = Awaited<ReturnType<typeof getMarketCandles>>,
  TError = ErrorType<unknown>,
>(
  params?: GetMarketCandlesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getMarketCandles>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMarketCandlesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns LSTM model forecast including direction probability and expected range
 * @summary Get LSTM price forecast
 */
export const getGetForecastUrl = (params?: GetForecastParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/forecast?${stringifiedParams}`
    : `/api/forecast`;
};

export const getForecast = async (
  params?: GetForecastParams,
  options?: RequestInit,
): Promise<ForecastOutput> => {
  return customFetch<ForecastOutput>(getGetForecastUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetForecastQueryKey = (params?: GetForecastParams) => {
  return [`/api/forecast`, ...(params ? [params] : [])] as const;
};

export const getGetForecastQueryOptions = <
  TData = Awaited<ReturnType<typeof getForecast>>,
  TError = ErrorType<unknown>,
>(
  params?: GetForecastParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getForecast>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetForecastQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getForecast>>> = ({
    signal,
  }) => getForecast(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getForecast>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetForecastQueryResult = NonNullable<
  Awaited<ReturnType<typeof getForecast>>
>;
export type GetForecastQueryError = ErrorType<unknown>;

/**
 * @summary Get LSTM price forecast
 */

export function useGetForecast<
  TData = Awaited<ReturnType<typeof getForecast>>,
  TError = ErrorType<unknown>,
>(
  params?: GetForecastParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getForecast>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetForecastQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns multi-agent trade intent and risk scores from NEAT networks
 * @summary Get NEAT agent decisions
 */
export const getGetAgentDecisionUrl = (params?: GetAgentDecisionParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/agents/decision?${stringifiedParams}`
    : `/api/agents/decision`;
};

export const getAgentDecision = async (
  params?: GetAgentDecisionParams,
  options?: RequestInit,
): Promise<AgentDecisionOutput> => {
  return customFetch<AgentDecisionOutput>(getGetAgentDecisionUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetAgentDecisionQueryKey = (
  params?: GetAgentDecisionParams,
) => {
  return [`/api/agents/decision`, ...(params ? [params] : [])] as const;
};

export const getGetAgentDecisionQueryOptions = <
  TData = Awaited<ReturnType<typeof getAgentDecision>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAgentDecisionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAgentDecision>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAgentDecisionQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAgentDecision>>
  > = ({ signal }) => getAgentDecision(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAgentDecision>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAgentDecisionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAgentDecision>>
>;
export type GetAgentDecisionQueryError = ErrorType<unknown>;

/**
 * @summary Get NEAT agent decisions
 */

export function useGetAgentDecision<
  TData = Awaited<ReturnType<typeof getAgentDecision>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAgentDecisionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAgentDecision>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAgentDecisionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns multi-agent aggregated signal with regime-based weights
 * @summary Get regime-weighted aggregation
 */
export const getGetAggregationUrl = (params?: GetAggregationParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/aggregate?${stringifiedParams}`
    : `/api/aggregate`;
};

export const getAggregation = async (
  params?: GetAggregationParams,
  options?: RequestInit,
): Promise<AggregationOutput> => {
  return customFetch<AggregationOutput>(getGetAggregationUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetAggregationQueryKey = (params?: GetAggregationParams) => {
  return [`/api/aggregate`, ...(params ? [params] : [])] as const;
};

export const getGetAggregationQueryOptions = <
  TData = Awaited<ReturnType<typeof getAggregation>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAggregationParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAggregation>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAggregationQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAggregation>>> = ({
    signal,
  }) => getAggregation(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAggregation>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAggregationQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAggregation>>
>;
export type GetAggregationQueryError = ErrorType<unknown>;

/**
 * @summary Get regime-weighted aggregation
 */

export function useGetAggregation<
  TData = Awaited<ReturnType<typeof getAggregation>>,
  TError = ErrorType<unknown>,
>(
  params?: GetAggregationParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAggregation>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAggregationQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns structured LLM-style reasoning context and confidence
 * @summary Get reasoning layer output
 */
export const getGetReasoningUrl = (params?: GetReasoningParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/reasoning?${stringifiedParams}`
    : `/api/reasoning`;
};

export const getReasoning = async (
  params?: GetReasoningParams,
  options?: RequestInit,
): Promise<ReasoningOutput> => {
  return customFetch<ReasoningOutput>(getGetReasoningUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetReasoningQueryKey = (params?: GetReasoningParams) => {
  return [`/api/reasoning`, ...(params ? [params] : [])] as const;
};

export const getGetReasoningQueryOptions = <
  TData = Awaited<ReturnType<typeof getReasoning>>,
  TError = ErrorType<unknown>,
>(
  params?: GetReasoningParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getReasoning>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReasoningQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReasoning>>> = ({
    signal,
  }) => getReasoning(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReasoning>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetReasoningQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReasoning>>
>;
export type GetReasoningQueryError = ErrorType<unknown>;

/**
 * @summary Get reasoning layer output
 */

export function useGetReasoning<
  TData = Awaited<ReturnType<typeof getReasoning>>,
  TError = ErrorType<unknown>,
>(
  params?: GetReasoningParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getReasoning>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetReasoningQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns combined decision from all 5 intelligence layers
 * @summary Get final decision engine output
 */
export const getGetFinalDecisionUrl = (params?: GetFinalDecisionParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/decision?${stringifiedParams}`
    : `/api/decision`;
};

export const getFinalDecision = async (
  params?: GetFinalDecisionParams,
  options?: RequestInit,
): Promise<FinalDecisionOutput> => {
  return customFetch<FinalDecisionOutput>(getGetFinalDecisionUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetFinalDecisionQueryKey = (
  params?: GetFinalDecisionParams,
) => {
  return [`/api/decision`, ...(params ? [params] : [])] as const;
};

export const getGetFinalDecisionQueryOptions = <
  TData = Awaited<ReturnType<typeof getFinalDecision>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFinalDecisionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getFinalDecision>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFinalDecisionQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFinalDecision>>
  > = ({ signal }) => getFinalDecision(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFinalDecision>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFinalDecisionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFinalDecision>>
>;
export type GetFinalDecisionQueryError = ErrorType<unknown>;

/**
 * @summary Get final decision engine output
 */

export function useGetFinalDecision<
  TData = Awaited<ReturnType<typeof getFinalDecision>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFinalDecisionParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getFinalDecision>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetFinalDecisionQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
